# Section 4: Intro to Numpy

In [1]:
import sys
import numpy as np

### Basic Arrays
Look like python lists but has differences
- pass it a list
- can access individual elements of array
- if separate elements by comma, get another numpy array of only those elements

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])
b = np.array([0,0.5,1,1.5,2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

### Array Types
- int, float, sizes
- created normally size 64

In [8]:
a.dtype

dtype('int64')

In [9]:
b.dtype

dtype('float64')

In [12]:
#creating an array with a specific type
np.array([1,2,3,4], dtype=np.float)

array([1., 2., 3., 4.])

In [13]:
#creating array with specific bit size
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [14]:
#can store strings, but numpy is better with numbers, booleans
c = np.array(['a','b','c'])

In [15]:
c.dtype

dtype('<U1')

### Dimensions and shapes
- shape = (rows, columns)
- dimension = vertical + horizontal
- size = number of individual elements

If dimensions of arrays don't match, can't do some operations with them.

In [16]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [17]:
A.shape

(2, 3)

In [18]:
A.ndim

2

In [19]:
A.size

6

In [20]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [21]:
B.shape

(2, 2, 3)

In [22]:
B.ndim

3

In [26]:
B.size

12

### Indexing and Slicing Matrixes

Similar to what we did before, but have to account for multiple dimensions

In [29]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9] 
])

In [30]:
#gives you second array in larger array
A[1]

array([4, 5, 6])

In [35]:
#gives you first elements of second array
A[1][0]
#can also write as A[1, 0]

4

In [32]:
#slices only 2 first arrays
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
#slices the first two elements of the first two arrays
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [37]:
#replacing one of the arrays
#dimensions need to match in order to do this
A[1] = np.array([10,10,10])

In [38]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [40]:
#or can do it like this and numpy will make sure to have right dimensions
A[2] = 99

In [41]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### Summary Statistics
- numpy has a bunch of operations to use on top of the arrays
for multiple dimensions, need to tell it which axis to do the operations on.

In [42]:
a = np.array([1, 2, 3, 4])

In [44]:
#sums all elements
a.sum()

10

In [45]:
a.mean()

2.5

In [47]:
#standard deviation
a.std()

1.118033988749895

In [48]:
a.var()

1.25

In [49]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [50]:
#adds everything
A.sum()

45

In [51]:
#sums of each column
A.sum(axis=0)

array([12, 15, 18])

In [52]:
#sums each row
A.sum(axis=1)

array([ 6, 15, 24])

### Broadcasting and Vectorized operations
Boolean arrays
- vectorized operations --> on more than one number, act on whole array
- can have operations between arrays as long as have same shape

In [60]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [61]:
a+10

array([10, 11, 12, 13])

In [62]:
a*10

array([ 0, 10, 20, 30])

In [63]:
#vectorized operations don't modify array, create a new one
a

array([0, 1, 2, 3])

In [64]:
#can do it by reassigning
a+=100
a

array([100, 101, 102, 103])

In [66]:
a = np.arange(4)
b = np.array([10,10,10,10])

In [67]:
a+b

array([10, 11, 12, 13])

In [68]:
a*b

array([ 0, 10, 20, 30])

### Boolean arrays
(also called masks)
- can use boolean operators to modify lists: and, or, >, <, etc.
- very useful for filtering our arrays

In [70]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [73]:
#selecting first and last elements
a[0], a[-1]

(0, 3)

In [76]:
#multi index way
a[[0,-1]]

array([0, 3])

In [77]:
#or can do it with boolean arrays.
a[[True, False, False, True]]

array([0, 3])

In [79]:
#results in boolean array giving info about elements of a
a>=2

array([False, False,  True,  True])

In [80]:
a[a>=2]

array([2, 3])

In [81]:
#new array with only elements greater than mean
a[a>a.mean()]

array([2, 3])

In [82]:
A = np.random.randint(100, size=(3, 3))
A

array([[80, 95, 76],
       [19, 92, 65],
       [88, 31, 89]])

In [83]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([80, 76, 92, 88, 89])

In [84]:
A > 80

array([[False,  True, False],
       [False,  True, False],
       [ True, False,  True]])

In [86]:
A[A>80]

array([95, 92, 88, 89])

### Linear Algebra
- have the operations already in numpy

In [87]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [88]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [89]:
#dot product
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [92]:
#another syntax for dot product
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [93]:
#transpose
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [94]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Useful Numpy Functions

#### random

In [96]:
np.random.random(size=2)

array([0.46014919, 0.58233572])

In [97]:
np.random.normal(size=2)

array([0.49171205, 0.64842427])

In [98]:
np.random.rand(2,4)

array([[0.13486886, 0.59733632, 0.20739013, 0.59227826],
       [0.99514199, 0.00642545, 0.68970107, 0.94615189]])

#### arange

In [99]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [101]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### reshape

In [103]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### linspace

In [105]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [106]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [107]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

#### zeros, ones, empty

In [108]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [110]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [111]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [113]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

#### identity and eye

In [114]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [115]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [116]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [117]:
np.eye(8,4,k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
'Hello World'[6]